name: Folder Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      run: echo "Triggered only for src folder"
